### ISSUE TITLE
其他一些公众号

### ISSUE THREAD

**Issue by tom0li** [DropsOfZut/awesome-security-weixin-official-accounts#1]
二向箔安全
Thorns的安全分享
Threathunter 
懒人学安全
07v8论安全
我的安全世界观  主要甲方建设
全频带阻塞干扰  关于隐私，侦探

**Comment by DropsOfZut** [comment]
已关注公众号，正在添加。“我的安全世界观”没有找到，麻烦给个链接。

**Comment by tom0li** [comment]
http://mp.weixin.qq.com/s/xDgrIQG7bdbkrgNpbsxSIQ
一片文章链接
